version: 2

jobs:
  build_and_test:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/docker-airflow
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build docker image
          command: |
            docker build -t us.gcr.io/data-etl-227416/scalefactor/docker-airflow .
      - run: 
          name: Test docker image
          command: |
            docker run us.gcr.io/data-etl-227416/scalefactor/docker-airflow version | grep '1.10.4'
      - run:
          name: Push docker image
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project data-etl-227416
            gcloud docker -- push us.gcr.io/data-etl-227416/scalefactor/docker-airflow

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
              branches:
                only: master

